#include "blocks.h"

const char *blockNames[Block::BLOCKS_COUNT] = {
    "Air",
    "Dirt",
    "Grass Block",
    "Stone",
    "Grass",
    "Sand",
    "Sand Ruby",
    "Sandstone",
    "Wood Plank",
    "Stone Bricks",
    "Clay",
    "Wood Log",
    "Leaves",
    "Copper",
    "Iron",
    "Gold",
    "Copper Block",
    "Iron Block",
    "Gold Block",
    "Bricks",
    "Snow",
    "Ice",
    "Ruby Block",
    "Platform",
    "Workbench",
    "Glass",
    "Furnace",
    "Painting",
    "Sapling",
    "Snow Blue Ruby",
    "Blue Ruby Block",
    "Door",
    "Jar",
    "Table",
    "Wardrobe",
    "Bookshelf",
    "Snow Bricks",
    "Ice Table",
    "Ice Wardrobe",
    "Ice Bookshelf",
    "Ice Platform",
    "Sand Table",
    "Sand Wardrobe",
    "Sand Bookshelf",
    "Sand Platform",
    "Wooden Chest",
    "Ice Chest",
    "Sand Chest",
    "Bone Chest",
    "Bone Bricks",
    "Bone Bench",
    "Bone Wardrobe",
    "Bone Bookshelf",
    "Bone Platform"};